services:
  - type: web
    name: ase-flask-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "TRUE"
    plan: free
